[[!comment format=mdwn
 username="joey"
 subject="""comment 6"""
 date="2018-10-30T16:23:21Z"
 content="""
I saw a different "SQLite3 returned ErrorIO while attempting to perform step",
which seems likely to be closely related to this problem.
(The "step" action happens right after the "prepare" action.)

	failed to commit changes to sqlite database: Just SQLite3 returned ErrorIO while attempting to perform step.
	CallStack (from HasCallStack):
	  error, called at ./Database/Handle.hs:116:26 in main:Database.Handle

The test suite occasionally fails due to this, and it seems always in 
`test_lock_v7_force`. Which notably deletes the sqlite database just before
the failure, and so causes it to be re-created.

Dumping the keys database after such a failure, it is freshly created,
contains the tables but no data has been written to it.

I've made git-annex catch ErrorIO and retry. Not sure if that fixes the bug,
but it may.

Please try, if you can, the new git-annex version 7, and see if this bug
still happens.
"""]]
