[[!comment format=mdwn
 username="kyle"
 avatar="http://cdn.libravatar.org/avatar/7d6e85cde1422ad60607c87fa87c63f3"
 subject="comment 15"
 date="2020-03-10T19:30:50Z"
 content="""
> If there's no obvious solution, I can probably just re-create the entire datalad dataset from scratch with the new software versions in this conda env.

It's not obvious to me why an uninstalled subdataset would be causing issues with the repo upgrade process.  Quickly trying, I can't trigger an issue, but perhaps the submodule got into some weird, not-really-removed state.  You can open an issue on DataLad's side and we can try to debug it, though doing so might be tricky without a recipe to trigger it.
"""]]
